server:
  port: ${PORT}

lavalink:
  server:
    password: "supersecret"
    sources:
      youtube: true
    ws:
      enabled: true

logging:
  file:
    max-history: 30
    max-size: 1GB
